services:
  web:
    # image: php:apache
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${port}:${port2}"
    volumes:
      - ./src/app/backend:/var/www/html
      - ./000-default.conf:/etc/apache2/conf.d/000-default.conf
